name: frist Workflow


on:
  push:
    branches:
      - main
jobs:
  example-jop:
    runs-on: ubuntu-latest

    steps:
      - name: Print a welcom message
        run: echo "welcom to our frist Github actions "

      - name: cheackout repo
        uses: actions/checkout@v2.8.0

      - name: list all files
        run: ls -la
      
         
        
      
  
      
  
