name: frist Workflow


on:
  push:
    branches:
      - main
jobs:
  example-jop:
    runs-on: ubuntu-latest

    steps:
      - name: Print a welcom message
        run: echo "welcom to our frist Github actions "
      
  
      
  
