on:
  push:
    branches:
      - main
      - "release/**"
  pull_request:
    branches:
      - main
      - "release/**"
    paths:
      - 'src/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v6

    - name: Update npm to the latest version
      run: npm install -g npm@latest


    - name: Clean npm cache
      run: npm cache clean --force


    - name: Delete node modules and package-lock.json
      run: |
        rm -rf node_modules
        rm package-lock.json


    - name: Install dependencies
      run: npm install


    - name: Run tests
      run: npm test